import React,{useEffect,useMemo,useState}from"react";
import{createRoot}from"react-dom/client";
import"./styles.css";
const emptyDraft={title:"Bilingual Handout / 双语讲义",blocks:[],passages:[]};
function App(){
 const[step,setStep]=useState(1),[file,setFile]=useState(null),[source,setSource]=useState(""),[references,setReferences]=useState([]),[overrides,setOverrides]=useState({}),[draft,setDraft]=useState(emptyDraft),[mode,setMode]=useState("bilingual"),[health,setHealth]=useState({}),[busy,setBusy]=useState(""),[error,setError]=useState("");
 useEffect(()=>{fetch("/api/health").then(r=>r.json()).then(setHealth).catch(()=>{})},[]);
 const configured=health.translationConfigured,statusText=useMemo(()=>[health.translationConfigured?"AI translation ready":"Demo translation",health.esvConfigured?"ESV connected":"ESV override mode",health.cuvsConfigured?"CUVS connected":"CUVS override mode"],[health]);
 async function importFile(){if(!file)return;setBusy("Reading document…");setError("");const form=new FormData();form.append("document",file);const res=await fetch("/api/import",{method:"POST",body:form}),json=await res.json();if(!res.ok){setError(json.error);setBusy("");return}setSource(json.text);setReferences(json.references);setStep(2);setBusy("")}
 async function generate(){setBusy(configured?"Translating and matching scripture…":"Building demo handout…");setError("");const res=await fetch("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:source,references,overrides,demo:!configured})}),json=await res.json();if(!res.ok){setError(json.error);setBusy("");return}setDraft(json);setStep(3);setBusy("")}
 async function exportFile(format){setBusy(format==="pdf"?"Preparing PDF handout…":"Preparing Word handout…");setError("");const res=await fetch(format==="pdf"?"/api/export/pdf":"/api/export",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...draft,outputMode:mode})});if(!res.ok){const json=await res.json();setError(json.error);setBusy("");return}const blob=await res.blob(),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`${mode}-handout.${format}`;a.click();URL.revokeObjectURL(url);setBusy("")}
 const updateBlock=(index,key,value)=>setDraft(current=>({...current,blocks:current.blocks.map((b,i)=>i===index?{...b,[key]:value}:b)}));
 return <main><header className="topbar"><a className="brand" href="#"><span className="mark">H</span><span>Handout Bridge</span></a><span className="eyebrow">EN → 简体中文</span></header>
 <section className="hero"><div><p className="kicker">Church handouts, without the formatting marathon</p><h1>From an English handout<br/>to a polished bilingual edition.</h1><p className="lede">Import an English Word or PDF handout, review scripture substitutions, refine the translation, then export in bilingual or Chinese-only format.</p></div><div className="status-card"><p className="mini-label">System readiness</p>{statusText.map((x,i)=><div className="status" key={x}><span className={i===0&&!configured?"dot amber":"dot"}/>{x}</div>)}</div></section>
 <nav className="steps" aria-label="Workflow">{["Import","Scripture","Review & export"].map((label,i)=><button key={label} className={step===i+1?"active":step>i+1?"done":""} onClick={()=>step>i+1&&setStep(i+1)}><span>0{i+1}</span>{label}</button>)}</nav>
 <section className="workspace">
 {step===1&&<div className="panel import-panel"><div className="panel-heading"><p className="mini-label">Step 01</p><h2>Bring in the English source</h2><p>DOCX and text-based PDF are supported up to 20 MB.</p></div><label className="dropzone"><input type="file" accept=".docx,.pdf" onChange={e=>setFile(e.target.files[0])}/><span className="upload-icon">↑</span><strong>{file?file.name:"Choose a document"}</strong><small>{file?`${(file.size/1024).toFixed(0)} KB · ready to import`:"or drag it here"}</small></label><button className="primary" disabled={!file||busy} onClick={importFile}>{busy||"Read document"} <span>→</span></button></div>}
 {step===2&&<div className="editor-grid"><div className="panel"><div className="panel-heading"><p className="mini-label">Source text</p><h2>Confirm the extraction</h2></div><textarea className="source-editor" value={source} onChange={e=>setSource(e.target.value)}/></div><div className="panel scripture-panel"><div className="panel-heading"><p className="mini-label">Detected scripture</p><h2>{references.length} passage{references.length===1?"":"s"} found</h2><p>Override any passage here. Blank fields use the configured ESV/CUVS source.</p></div>{references.length===0&&<div className="empty">No Bible references detected. You can continue and translate the handout as-is.</div>}{references.map(ref=><div className="verse-card" key={ref}><div className="verse-title"><strong>{ref}</strong><span>ESV · CUVS</span></div><textarea placeholder="Optional ESV override" value={overrides[ref]?.english||""} onChange={e=>setOverrides({...overrides,[ref]:{...overrides[ref],english:e.target.value}})}/><textarea placeholder="可选的和合本经文替换" value={overrides[ref]?.chinese||""} onChange={e=>setOverrides({...overrides,[ref]:{...overrides[ref],chinese:e.target.value}})}/></div>)}<button className="primary" disabled={!source.trim()||busy} onClick={generate}>{busy||(configured?"Generate handout":"Generate demo handout")} <span>→</span></button>{!configured&&<p className="hint">Add OPENAI_API_KEY to .env for production-quality translation. Demo mode keeps the entire UI testable now.</p>}</div></div>}
 {step===3&&<div className="review-layout"><aside className="panel controls"><div className="panel-heading"><p className="mini-label">Output</p><h2>Choose a handout</h2></div>{[["bilingual","Bilingual","English + 简体中文"],["chinese","Chinese only","仅简体中文"],["english","English only","Source language"]].map(([value,label,sub])=><label className={`mode ${mode===value?"selected":""}`} key={value}><input type="radio" name="mode" checked={mode===value} onChange={()=>setMode(value)}/><span><strong>{label}</strong><small>{sub}</small></span></label>)}<div className="export-actions"><button className="primary" disabled={busy} onClick={()=>exportFile("docx")}>{busy||"Download DOCX"} <span>↓</span></button><button className="primary pdf" disabled={busy} onClick={()=>exportFile("pdf")}>{busy||"Download PDF"} <span>↓</span></button></div><button className="secondary" onClick={()=>setStep(2)}>← Edit source & scripture</button></aside><article className="paper"><input className="title-editor" value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/><p className="language-line">{mode==="bilingual"?"ENGLISH · 简体中文":mode==="chinese"?"简体中文":"ENGLISH"}</p>{draft.passages?.map(p=><div className={`passage ${mode}`} key={p.reference}>{mode!=="chinese"&&p.english?.text&&<div><strong>{p.reference} (ESV)</strong><p>{p.english.text}</p><small>{p.english.source}</small></div>}{mode!=="english"&&<div><strong>{p.reference}（和合本）</strong><p>{p.chinese?.text||"请提供 CUVS 经文或配置 API.Bible。"}</p><small>{p.chinese?.source||"Needs source"}</small></div>}</div>)}{draft.blocks.map((block,i)=><div className={`block ${block.type} ${mode}`} key={i}>{mode!=="chinese"&&<textarea value={block.english} onChange={e=>updateBlock(i,"english",e.target.value)}/>} {mode!=="english"&&<textarea lang="zh-Hans" value={block.chinese} onChange={e=>updateBlock(i,"chinese",e.target.value)}/>}</div>)}</article></div>}
 {error&&<div className="error">{error}</div>}</section><footer><span>Designed from your 2025–2026 handout archive.</span><span>Local-first · keys stay on your machine</span></footer></main>
}
createRoot(document.getElementById("root")).render(<App/>);
